artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion
  source_path: data/audio-genre-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  model_path: artifacts/prepare_base_model/model.h5
  