artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_path: data/audio-genre-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_data:
  root_dir: artifacts/prepare_data
  source_dir: artifacts/data_ingestion/genres_original/
  target_dir: artifacts/prepare_data/mfcc_3sec_chunks.json
  train_data_path: artifacts/prepare_data/train_data.json
  test_data_path: artifacts/prepare_data/test_data.json
  val_data_path: artifacts/prepare_data/val_data.json  

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  model_path: artifacts/prepare_base_model/model.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/best_model.h5

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model.h5
  